# Basic
title: Brain Wash
subtitle: Facts don't matter.People are irrational.

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://www.jianshu.com/u/3d71cd3465f4'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: brain-wash
    
#RSSread
name:         Brain Wash  
description:  A hirtory of my brainwave.  
url:          http://yangaijun.com/ 
